[package]
name = "termgpt"
version = "0.1.0"
edition = "2021"

[dependencies]
termion = { version = "2.0.1" }
hyper = { version = "0.14", features = ["full"] }
hyper-tls = { version = "0.5" }
regex = { version = "1" }
serde = { version = "1" }
serde_json = { version = "1" }
tokio = { version = "1", features = ["full"] }
toml = { version = "0.6" }
