name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  TOOLCHAIN: stable

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - run: |
          rustup update $TOOLCHAIN
          rustup default $TOOLCHAIN

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: 'test'

      - run: cargo test
